name: CI-CD

on:
  push:
    branches: 
      - feature/*
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: | 
          mvn test -Ddb.host=${{ secrets.DATASOURCE_HOST }} -Ddb.port=${{ secrets.DATASOURCE_PORT }} -Ddb.username=${{ secrets.DATASOURCE_USERNAME }} -Ddb.password=${{ secrets.DATASOURCE_PASSWORD }} -Ddb.database=${{ secrets.DATASOURCE_DATABASE }}
